"""initial schema: sources, articles, user_settings

Revision ID: 22b34bcc0f7a
Revises: 
Create Date: 2026-04-26 23:45:11.156584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22b34bcc0f7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('url_normalized', sa.Text(), nullable=False),
    sa.Column('url_original', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sources', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('status', sa.Enum('unscored', 'scored', 'score_failed', name='article_status'), server_default=sa.text("'unscored'"), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('score_reasoning', sa.Text(), nullable=True),
    sa.Column('low_content_confidence', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_with_interest_version', sa.Integer(), nullable=True),
    sa.Column('score_failure_reason', sa.Text(), nullable=True),
    sa.Column('is_backfill', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sent_in_digest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score IS NULL OR (score BETWEEN 0 AND 100)', name='ck_articles_score_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url_normalized', name='uq_articles_user_url')
    )
    op.create_index('ix_articles_status', 'articles', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('rss', name='source_type'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('ai_engineering', 'ai_policy', 'politics', name='category'), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=2), server_default=sa.text('1.0'), nullable=False),
    sa.Column('poll_interval_minutes', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_poll_status', sa.Enum('ok', 'failed', name='poll_status'), nullable=True),
    sa.Column('last_poll_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('consecutive_failures >= 0', name='ck_sources_failures_nonneg'),
    sa.CheckConstraint('poll_interval_minutes >= 1', name='ck_sources_poll_interval_min'),
    sa.CheckConstraint('weight >= 0.1 AND weight <= 10.0', name='ck_sources_weight_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_sources_user_name'),
    sa.UniqueConstraint('user_id', 'url', name='uq_sources_user_url')
    )
    op.create_index('ix_sources_enabled_last_polled', 'sources', ['enabled', 'last_polled_at'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('interests_text', sa.Text(), nullable=False),
    sa.Column('interests_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('digest_time_local', sa.String(length=5), server_default=sa.text("'07:00'"), nullable=False),
    sa.Column('digest_timezone', sa.String(length=64), server_default=sa.text("'Asia/Jakarta'"), nullable=False),
    sa.Column('score_threshold', sa.Integer(), server_default=sa.text('50'), nullable=False),
    sa.Column('digest_max_items', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('category_caps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('digest_max_items >= 1', name='ck_user_settings_max_items_min'),
    sa.CheckConstraint('interests_version >= 1', name='ck_user_settings_version_min'),
    sa.CheckConstraint('score_threshold BETWEEN 0 AND 100', name='ck_user_settings_score_threshold_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_settings_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_index('ix_sources_enabled_last_polled', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_articles_status', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
