"""unique constraints: nulls not distinct for single-user dedup

Revision ID: c6f6908fb6ed
Revises: 22b34bcc0f7a
Create Date: 2026-04-27 00:01:53.955335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f6908fb6ed'
down_revision: Union[str, Sequence[str], None] = '22b34bcc0f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_articles_user_url'), 'articles', type_='unique')
    op.create_unique_constraint('uq_articles_user_url', 'articles', ['user_id', 'url_normalized'], postgresql_nulls_not_distinct=True)
    op.drop_constraint(op.f('uq_sources_user_name'), 'sources', type_='unique')
    op.create_unique_constraint('uq_sources_user_name', 'sources', ['user_id', 'name'], postgresql_nulls_not_distinct=True)
    op.drop_constraint(op.f('uq_sources_user_url'), 'sources', type_='unique')
    op.create_unique_constraint('uq_sources_user_url', 'sources', ['user_id', 'url'], postgresql_nulls_not_distinct=True)
    op.drop_constraint(op.f('uq_user_settings_user'), 'user_settings', type_='unique')
    op.create_unique_constraint('uq_user_settings_user', 'user_settings', ['user_id'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_settings_user', 'user_settings', type_='unique')
    op.create_unique_constraint(op.f('uq_user_settings_user'), 'user_settings', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_sources_user_url', 'sources', type_='unique')
    op.create_unique_constraint(op.f('uq_sources_user_url'), 'sources', ['user_id', 'url'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_sources_user_name', 'sources', type_='unique')
    op.create_unique_constraint(op.f('uq_sources_user_name'), 'sources', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_articles_user_url', 'articles', type_='unique')
    op.create_unique_constraint(op.f('uq_articles_user_url'), 'articles', ['user_id', 'url_normalized'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
